"""initial_schema

Revision ID: ce2e9b4b4077
Revises: 
Create Date: 2026-07-14 20:37:39.531615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2e9b4b4077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catedras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cuota_vcpus', sa.Integer(), nullable=False),
    sa.Column('cuota_ram_mb', sa.Integer(), nullable=False),
    sa.Column('cuota_storage_gb', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('recurso_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('LXC', 'QEMU', name='tiporecurso'), nullable=False),
    sa.Column('default_vcpus', sa.Integer(), nullable=False),
    sa.Column('default_ram_mb', sa.Integer(), nullable=False),
    sa.Column('default_disk_gb', sa.Integer(), nullable=False),
    sa.Column('os_template', sa.String(length=200), nullable=True),
    sa.Column('config_extra', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_habilitado', sa.Boolean(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'CATEDRA_ADMIN', name='rolusuario'), nullable=False),
    sa.Column('catedra_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catedra_id'], ['catedras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catedra_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('SOLICITADO', 'EN_REVISION', 'APROBADO', 'EN_DESPLIEGUE', 'ACTIVO', 'RECHAZADO', 'ERROR', 'SUSPENDIDO', name='estadopedido'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('parametros_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catedra_id'], ['catedras.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['recurso_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catedra_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('proxmox_vmid', sa.String(length=10), nullable=True),
    sa.Column('proxmox_node', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.Enum('RUNNING', 'STOPPED', 'PAUSED', 'ERROR', name='estadoservicio'), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('vcpus_asignados', sa.Integer(), nullable=False),
    sa.Column('ram_asignada_mb', sa.Integer(), nullable=False),
    sa.Column('disk_asignado_gb', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catedra_id'], ['catedras.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['recurso_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_table('metricas_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=False),
    sa.Column('ram_usage_mb', sa.Float(), nullable=False),
    sa.Column('disk_usage_gb', sa.Float(), nullable=False),
    sa.Column('net_in_bytes', sa.Float(), nullable=False),
    sa.Column('net_out_bytes', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metricas_snapshots')
    op.drop_table('servicios')
    op.drop_table('pedidos_historial')
    op.drop_table('pedidos')
    op.drop_table('usuarios')
    op.drop_table('recurso_templates')
    op.drop_table('catedras')
    # ### end Alembic commands ###
